### ISSUE TITLE
Avoid realocation with tenmat and permutedims

### ISSUE THREAD

**Issue by raphaelchinchilla** [lanaperisa/TensorToolbox.jl#13]
It seems that tenmat allocates new arrays. This is not the behavior of reshape which simply defines a new view for the array. I think this could be modified by using PermutedDimsArray instead of permutedims, but I am not sure.

**Comment by lanaperisa** [comment]
Hi, thanks for the suggestion! However, I don't see how to do it, using PermutedDimsArray is not doing it. If you figure out a way, let me know, I will be happy to include it in the code.

**Comment by raphaelchinchilla** [comment]
Sorry I did not answer, I was busy. How are you checking whether "using PermutedDimsArray is not doing it". 

Is it by checking the objectid ? If so, I think that PermutedDimsArray create a new object but this object shares memory, so objectid does not seem to be the right tool for that.

In my tests, to check whether the two objects share memory, I do an inplace allocation of one and then check whether this change the other. Notice that currently, it seems that tenmat(A,1) shares storage, but not tenmat(A,n) n!=1.

**Comment by lanaperisa** [comment]
Hey, sorry, now I've been busy.. I actually don't remember how I checked it, somehow looking at memory location, but can't say how exactly.  Now thinking about it, the way I mostly use it, reshape is suppose to create a new object. I see that for some cases it would be useful not to, but meh.. :)
