### ISSUE TITLE
cp_als not exported??

### ISSUE THREAD

**Issue by kevin-w-li** [lanaperisa/TensorToolbox.jl#3]
I am on julia 0.6, and the function cp_als cannot be imported. There is a warning:
```
julia> import TensorToolbox: cp_als

WARNING: deprecated syntax "function .*(...)".
Use "function Base.broadcast(::typeof(*), ...)" instead.
WARNING: could not import TensorToolbox.cp_als into Main`
```
Thank you!

**Comment by lanaperisa** [comment]
Have you updated the package? 

I fixed the problem from the first warning and also created cp_als in the last version of the package, so hopefully updating to the new version will help.. Let me know!

**Comment by kevin-w-li** [comment]
Everything seems good now. Thank you for providing such a nice toolbox :)
