### ISSUE TITLE
extend to complex valued tensors

### ISSUE THREAD

**Issue by fhenneke** [lanaperisa/TensorToolbox.jl#6]
Hi,
I want to use the `TensorToolbox` for complex valued arrays. Do you intend to extend the package in this direction? The function definitions look like general number types would be supported. But at the moment it does not work since there are a lot of `zeros(n, m)` calls which default to the type `Float64`.
Best,
Felix

**Comment by lanaperisa** [comment]
Hi Felix,
I didn't have that in my plan, however I am interested in how that could work. Maybe I can try to do it on a smaller set of functions as a test. Are there some particular functions that you want to use for a start, so I can try it on them? Thanks!

**Comment by fhenneke** [comment]
Hi,
I noticed that it already works for some functions, like for `hosvd`, if I use the default `method = "svd"`.
```
x = rand(Complex{Float64}, 5, 4, 3)
hosvd(x, method = "svd")
```
I would be interested in using this function for other methods, but then it errors. In one case because of the creation of a symmetric matrix instead of a Hermitian one.
```
hosvd(x, method="randsvd")
```
 And in another case because a complex number would be written to a real array.
```
hosvd(x, method="lanczos")
```
I use complex tensors since my problem comes from quantum mechanics. It might be that a decomposition into real and imaginary part would be sufficient for my application, but a treatment of complex numbers should fall well into the mathematical setup of tensor methods.

**Comment by lanaperisa** [comment]
OK, so I adjusted the algorithms, now you can use method="randsvd" and method="lanczos" for complex tensors. Let me know if it works good!

**Comment by fhenneke** [comment]
Thank you for fixing this so fast! :) It works perfectly now for `hosvd`.
Would you appreciate a pull request with additional changes to make the package work better with complex data (or data with BigFloats, or DualNumbers, ...)? For example, addition of complex TT fails, as well as `htrunc` for hierarchical tensors.

**Comment by lanaperisa** [comment]
Yes, that would be great!  Go ahead :)
