### ISSUE TITLE
error in htrunc for non-default method

### ISSUE THREAD

**Issue by fhenneke** [lanaperisa/TensorToolbox.jl#7]
Hi,
there seem to be some issues with (renaming of?) supported keyword arguments in the function `colspace` which makes the function `htrunc` fail for non-default `method` arguments like `"randsvd"` or `"lanczos"`.
```
x = rand(5, 4, 3)
htrunc(x, method="svd")
```
works, but
```
x = rand(5, 4, 3)
htrunc(x, method="randsvd")
# htrunc(x, method="lanczos")
```
fails. Similarly
```
y = rand(5, 4)
colspace(y, method="svd")
```
works, but
```
y = rand(5, 4)
colspace(y, method="randsvd")
# colspace(y, method="lanczos")
```
fails.
Best, Felix

**Comment by lanaperisa** [comment]
Hey, sorry for a bit delayed replay.. I've fixed these issues, let me know if it's ok now!

**Comment by fhenneke** [comment]
Its work now. Thanks for the quick fix! :)

**Comment by lanaperisa** [comment]
Thank you, and please let me know when you find more bugs! :)
